default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres_user
  password: postgres_root
  host: db-postgres
development:
  <<: *default
  database: app
test:
  <<: *default
  database: app_test
production:
  <<: *default
  database: app_production